# Generated by finops_agent
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      CostCenter  = "unassigned"
      Owner       = "platform"
      Environment = "shared"
    }
  }
}


# ═══════════════════════════════════════════════════════════════
# Component 1/3 · seeded from L3-038
# ═══════════════════════════════════════════════════════════════

resource "aws_eks_cluster" "comp1_eks-cluster-pkd6k6" {
  name     = "prod-main"
  role_arn = aws_iam_role.eks-cluster-pkd6k6_cluster_role.arn
  version  = "1.28"

  vpc_config {
    subnet_ids = var.private_subnet_ids
  }

  tags = {
    Name = "eks-cluster-pkd6k6"
  }
}

resource "aws_instance" "comp1_instance-v0ektn" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-v0ektn"
  }
}

resource "aws_instance" "comp1_instance-xywbs0" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-xywbs0"
  }
}

resource "aws_instance" "comp1_instance-92mtlz" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-92mtlz"
  }
}

resource "aws_instance" "comp1_instance-ij9snq" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-ij9snq"
  }
}

resource "aws_instance" "comp1_instance-0w7cj6" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-0w7cj6"
  }
}

resource "aws_instance" "comp1_instance-a1zgs0" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-a1zgs0"
  }
}

resource "aws_instance" "comp1_instance-o7vva7" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-o7vva7"
  }
}

resource "aws_instance" "comp1_instance-vz40u3" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-vz40u3"
  }
}

resource "aws_instance" "comp1_instance-r324gy" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-r324gy"
  }
}

resource "aws_instance" "comp1_instance-qfvjou" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-qfvjou"
  }
}

resource "aws_instance" "comp1_instance-dhik62" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-dhik62"
  }
}

resource "aws_instance" "comp1_instance-nr5xcq" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-nr5xcq"
  }
}

resource "aws_instance" "comp1_instance-01drud" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-01drud"
  }
}

resource "aws_instance" "comp1_instance-yv666q" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-yv666q"
  }
}

resource "aws_instance" "comp1_instance-kiyrpa" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-kiyrpa"
  }
}

resource "aws_instance" "comp1_instance-csr5nu" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-csr5nu"
  }
}

resource "aws_instance" "comp1_instance-mf923m" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-mf923m"
  }
}

resource "aws_instance" "comp1_instance-mk1qxs" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-mk1qxs"
  }
}

resource "aws_instance" "comp1_instance-c1qec6" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-c1qec6"
  }
}

resource "aws_instance" "comp1_instance-rntl0o" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-rntl0o"
  }
}

resource "aws_instance" "comp1_instance-1wt0ct" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-1wt0ct"
  }
}

resource "aws_instance" "comp1_instance-x926ma" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-x926ma"
  }
}

resource "aws_instance" "comp1_instance-y6tend" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-y6tend"
  }
}

resource "aws_instance" "comp1_instance-y8jtb9" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-y8jtb9"
  }
}

resource "aws_instance" "comp1_instance-xzjcj6" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-xzjcj6"
  }
}

# ═══════════════════════════════════════════════════════════════
# Component 2/3 · seeded from L1-009
# ═══════════════════════════════════════════════════════════════

resource "aws_ecr_repository" "comp2_ecr-repository-xps9mi" {
  name                 = "ecr-repository-xps9mi"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "ecr-repository-xps9mi"
  }
}

resource "aws_ecr_repository" "comp2_ecr-repository-1ixrd2" {
  name                 = "ecr-repository-1ixrd2"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "ecr-repository-1ixrd2"
  }
}

resource "aws_ecr_repository" "comp2_ecr-repository-adv88d" {
  name                 = "ecr-repository-adv88d"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "ecr-repository-adv88d"
  }
}

resource "aws_ecr_repository" "comp2_ecr-repository-fnvv9e" {
  name                 = "ecr-repository-fnvv9e"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "ecr-repository-fnvv9e"
  }
}

resource "aws_ecr_lifecycle_policy" "comp2_ecr-repository-fnvv9e" {
  repository = aws_ecr_repository.comp2_ecr-repository-fnvv9e.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 images"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = 10
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}

resource "aws_ecr_repository" "comp2_ecr-repository-y2tc8r" {
  name                 = "ecr-repository-y2tc8r"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name = "ecr-repository-y2tc8r"
  }
}

resource "aws_ecr_lifecycle_policy" "comp2_ecr-repository-y2tc8r" {
  repository = aws_ecr_repository.comp2_ecr-repository-y2tc8r.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 images"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = 10
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}

# ═══════════════════════════════════════════════════════════════
# Component 3/3 · seeded from L3-031
# ═══════════════════════════════════════════════════════════════

resource "aws_instance" "comp3_instance-nrh160" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-nrh160"
  }
}

resource "aws_instance" "comp3_instance-9izaeq" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-9izaeq"
  }
}

resource "aws_instance" "comp3_instance-8ovc2w" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-8ovc2w"
  }
}

resource "aws_instance" "comp3_instance-1t9bk5" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-1t9bk5"
  }
}

resource "aws_instance" "comp3_instance-6vvvq3" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-6vvvq3"
  }
}

resource "aws_instance" "comp3_instance-938nl4" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-938nl4"
  }
}

resource "aws_instance" "comp3_instance-m21wqp" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "c5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-m21wqp"
    environment = "production"
  }
}

resource "aws_instance" "comp3_instance-q66vqs" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "c5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-q66vqs"
    environment = "production"
  }
}

resource "aws_instance" "comp3_instance-91881g" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "c5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-91881g"
    environment = "production"
  }
}

resource "aws_instance" "comp3_instance-jaxx0c" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "c5.xlarge"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-jaxx0c"
    environment = "production"
  }
}

resource "aws_db_instance" "comp3_db-instance-hcvhbn" {
  identifier     = "db-instance-hcvhbn"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-hcvhbn"
  }
}

resource "aws_db_instance" "comp3_db-instance-pwb4d7" {
  identifier     = "db-instance-pwb4d7"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-pwb4d7"
  }
}

resource "aws_db_instance" "comp3_db-instance-ctvwcq" {
  identifier     = "db-instance-ctvwcq"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-ctvwcq"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-l807nb" {
  bucket = "s3-bucket-l807nb"

  tags = {
    Name        = "s3-bucket-l807nb"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-4fkexv" {
  bucket = "s3-bucket-4fkexv"

  tags = {
    Name        = "s3-bucket-4fkexv"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-3yzv09" {
  bucket = "s3-bucket-3yzv09"

  tags = {
    Name        = "s3-bucket-3yzv09"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-ebo0s9" {
  bucket = "s3-bucket-ebo0s9"

  tags = {
    Name        = "s3-bucket-ebo0s9"
  }
}

resource "aws_lb" "comp3_lb-3knz5j" {
  name               = "lb-3knz5j"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.lb-3knz5j_sg.id]
  subnets = var.public_subnet_ids

  tags = {
    Name = "lb-3knz5j"
    team = "platform"
  }
}

resource "aws_lb" "comp3_lb-1yo5cr" {
  name               = "lb-1yo5cr"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.lb-1yo5cr_sg.id]
  subnets = var.public_subnet_ids

  tags = {
    Name = "lb-1yo5cr"
    team = "platform"
  }
}

resource "aws_lb" "comp3_lb-0h02me" {
  name               = "lb-0h02me"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.lb-0h02me_sg.id]
  subnets = var.public_subnet_ids

  tags = {
    Name = "lb-0h02me"
    team = "platform"
  }
}

resource "aws_instance" "comp3_instance-1xmxwn" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-1xmxwn"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_instance" "comp3_instance-o11g90" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-o11g90"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_instance" "comp3_instance-gn3c4j" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-gn3c4j"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_instance" "comp3_instance-nifwr7" {
  ami           = "ami-0abcdef1234567890"
  instance_type = "m5.large"
  subnet_id     = aws_subnet.main.id

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    delete_on_termination = true
  }

  tags = {
    Name        = "instance-nifwr7"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_db_instance" "comp3_db-instance-cl84rz" {
  identifier     = "db-instance-cl84rz"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-cl84rz"
    cost-center = "CC-1002"
    team = "data"
    environment = "production"
    project = "analytics"
  }
}

resource "aws_db_instance" "comp3_db-instance-y97hun" {
  identifier     = "db-instance-y97hun"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-y97hun"
    cost-center = "CC-1002"
    team = "data"
    environment = "production"
    project = "analytics"
  }
}

resource "aws_db_instance" "comp3_db-instance-pcqnah" {
  identifier     = "db-instance-pcqnah"
  engine         = "postgres"
  engine_version = "8.0"
  instance_class = "db.r5.large"

  allocated_storage = 100
  storage_type      = "gp3"

  multi_az = false

  backup_retention_period = 7

  skip_final_snapshot = false

  tags = {
    Name        = "db-instance-pcqnah"
    cost-center = "CC-1002"
    team = "data"
    environment = "production"
    project = "analytics"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-7ig1qg" {
  bucket = "s3-bucket-7ig1qg"

  tags = {
    Name        = "s3-bucket-7ig1qg"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-lvm4g1" {
  bucket = "s3-bucket-lvm4g1"

  tags = {
    Name        = "s3-bucket-lvm4g1"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}

resource "aws_s3_bucket" "comp3_s3-bucket-zmoi68" {
  bucket = "s3-bucket-zmoi68"

  tags = {
    Name        = "s3-bucket-zmoi68"
    cost-center = "CC-1001"
    team = "backend"
    environment = "production"
    project = "api-gateway"
  }
}


resource "aws_ecr_lifecycle_policy" "comp2_ecr-repository-xps9mi_lifecycle" {
  repository = aws_ecr_repository.comp2_ecr-repository-xps9mi.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Expire old images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 30
      }
      action = {
        type = "expire"
      }
    }]
  })
}


resource "aws_ecr_lifecycle_policy" "comp2_ecr-repository-1ixrd2_lifecycle" {
  repository = aws_ecr_repository.comp2_ecr-repository-1ixrd2.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Expire old images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 30
      }
      action = {
        type = "expire"
      }
    }]
  })
}


resource "aws_ecr_lifecycle_policy" "comp2_ecr-repository-adv88d_lifecycle" {
  repository = aws_ecr_repository.comp2_ecr-repository-adv88d.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Expire old images"
      selection = {
        tagStatus   = "any"
        countType   = "imageCountMoreThan"
        countNumber = 30
      }
      action = {
        type = "expire"
      }
    }]
  })
}
